version: 2.1

orbs:
  node: circleci/node@1.1

jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run: echo "Clean compile chrome-engine" # This prints "A first hello" to stdout.
      - run: sh "npm --no-color --unsafe-perm ci"
  runUnitTests: # this job requries job 'build'
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - run: echo "Run unit tests"
  runIntegrationTests: # this job requires job 'build' TODO
    executor:
      name: node/default
      tag: '10.4'
    steps:
        - run: echo "Run integration tests"
  updateRancher: # update rancher config to use the latest image, applicable for both journey and audits TODO
    executor:
      name: node/default
      tag: '10.4'
    steps:
        - run: echo "Updating rancher to use the latest image"

# -------------------------------------
# ----- Web-journey-specific Jobs -----
# -------------------------------------
  storeDockerImageToECR: # TODO
    executor:
      name: node/default
      tag: '10.4'
    steps:
        - run: echo "Registering Docker image to ECR"
  updateFargate:
    executor:
      name: node/default
      tag: '10.4'
    steps:
        - run: echo "Updating Fartgate config using the latest image on ECR"

# -----------------------------------
# ----- Web-audit-specific Jobs -----
# -----------------------------------
  storeDockerImageToNexus: # TODO
    executor:
      name: node/default
      tag: '10.4'
    steps:
        - run: echo "Registering Docker image to ECR"
  recordContainerIdInConsole: # TODO
    executor:
      name: node/default
      tag: '10.4'
    steps:
        - run: echo "Recording image id in console"
  restartBestow: # TODO
    executor:
      name: node/default
      tag: '10.4'
    steps:
        - run: echo "Restarting Bestw

# workflows section: typed by each engine usage
workflows:
  version: 2.1 
  DefaultWorkFlow: # this workflow build the project and run the tests
    jobs:
      - build
      - runUnitTests:
          requires:
            - build
      - runIntegrationTests:
          requires:
            - build

  # Optional Work Flows
  DeployAuditEngineOnProd: # this optional workflow deploys the audit engine
    jobs: 
      - build
      - runUnitTests:
          requires:
            - build
      - runIntegrationTests:
          requires:
            - build
  DeployAuditEngineOnStaging: # this optional workflow deploys the audit engine
    jobs: 
      - build
      - runUnitTests:
          requires:
            - build
      - runIntegrationTests:
          requires:
            - build
  DeployWebJourneyEngineOnProd: # this optional workflow deploys the web journey engine
    jobs:
      - build
      - runUnitTests:
          requires:
            - build
      - runIntegrationTests:
          requires:
            - build
  DeployWebJourneyEngineOnStaging: # this optional workflow deploys the web journey engine
    jobs:
      - build
      - runUnitTests:
          requires:
            - build
      - runIntegrationTests:
          requires:
            - build
